---

- name: 実行ユーザ名と同じ名前のグループの作成
  become: yes
  group:
    name: "{{ execute_user.name }}"
    gid: "{{ execute_user.gid }}"

- name: 実行ユーザの作成
  become: yes
  user:
    name: "{{ execute_user.name }}"
    password: "{{ execute_user.password | string | password_hash('sha512') }}"
    uid: "{{ execute_user.uid }}"
    group: "{{ execute_user.name }}"
    groups: "{% if ansible_os_family == 'Debian' %}{{ execute_user.debian_groups }}{% else %}{{ execute_user.redhat_groups }} {% endif %}" # サブグループ
    shell: /bin/bash
    update_password: on_create
    state: present
    createhome: yes
