---

master:
  hosts:
    master-1:
      ansible_host: 192.168.34.101
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_become_password: vagrant
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

replicas:
  hosts:
    replica-1:
      ansible_host: 192.168.34.102
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_become_password: vagrant
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    replica-2:
      ansible_host: 192.168.34.103
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_become_password: vagrant
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
