---

version: "3.7"

services:
  app:
    image: digdag-ls
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      IS_MASTER: "false"
      ENV: $ENV
      EXEC_USER: $EXEC_USER
      EXEC_UID: $EXEC_UID
      EXEC_GID: $EXEC_GID
    volumes:
      - sshfs_volume:$DATA_HOME

volumes:
  sshfs_volume:
    name: sshfs_volume
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: ${SSHFS_USER}@${SSHFS_MASTER_HOST}:${DATA_HOME}
      IdentityFile: /root/.ssh/${SSHFS_IDENTITY_FILE}
      allow_other: ""
      #ro: ""
