---

version: "3.7"

services:
  app:
    image: digdag-ls
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IS_MASTER: "true"
      ENV: $ENV
      EXEC_USER: $EXEC_USER
      EXEC_UID: $EXEC_UID
      EXEC_GID: $EXEC_GID
      SLACK_INCOMING_WEBHOOK_URL: $SLACK_INCOMING_WEBHOOK_URL
    working_dir: /app
    volumes:
      - .:/app
