---

version: "3.7"

services:
  app:
    image: digdag-ls
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UID: 10001
      GID: 10001
    volumes:
      - sshfs_volume:/var/hoge/fuga/data:ro
      - $MOUNT_DATA:/var/a/b/c/data

volumes:
  sshfs_volume:
    name: sshfs_volume
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: ${SSHFS_USER}@${SSHFS_SRC_MASTER_HOST}:${SSHFS_SRC_PATH}
      IdentityFile: /root/.ssh/${SSHFS_IDENTITY_FILE}
      allow_other: ""
      ro: ""
