---

# 受け取る側
- name: 公開鍵の配布
  authorized_key:
    user: "{{ execute_user.name }}"
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "replica_pub_keys/*.pub"
  when: "'master' in group_names"

# 作る側
- name: "{{ execute_user.name }}のsshkeyの作成(userモジュールで)"
  user:
    name: "{{ execute_user.name }}"
    generate_ssh_key: yes
    ssh_key_comment: ""
    ssh_key_file: ".ssh/{{ app.name }}"
    ssh_key_type: ed25519
  when: "'replicas' in group_names"

- name: 公開鍵のダウンロード
  fetch:
    src: "/home/{{ execute_user.name }}/.ssh/{{ app.name }}.pub"
    dest: "./replica_pub_keys/{{ inventory_hostname }}.pub"
    flat: true
  when: "'replicas' in group_names"
