---

- name: アプリ用ディレクトリを作成
  become: yes
  file:
    path: "{{ app.dest_path }}"
    state: directory
    owner: "{{ execute_user.name }}"
    group: "{{ execute_user.name }}"
    mode: 0744

- name: git clone repository
  become: yes
  git:
    repo: "{{ app.src_repo }}"
    dest: "{{ app.dest_path }}/{{ app.version_dir }}"
    version: "{{ app.deploy_branch }}"

- name: docker-compose build
  become: yes
  command: "docker-compose -f {{ app.docker_compose_file }} build"
  args:
    chdir: "{{ app.dest_path }}/{{ app.version_dir }}/{{ app.docker_compose_context }}"

- name: 実行環境(vagrant/alpha/beta/live)に合わせた.envの用意
  become: yes
  command: "cp profile/env.{{ app.env }} .env"
  args:
    chdir: "{{ app.dest_path }}/{{ app.version_dir }}/{{ app.docker_compose_context }}"

- name: "docker-compose -f {{ app.docker_compose_file }} down"
  become: yes
  command: "docker-compose -f {{ app.docker_compose_file }} down"
  args:
    chdir: "{{ app.dest_path }}/{{ app.version_dir }}/{{ app.docker_compose_context }}"

- name: "{{ execute_user.name }}で実行"
  become: yes
  become_user: "{{ execute_user.name }}"
  command: "docker-compose -f {{ app.docker_compose_file }} up -d"
  args:
    chdir: "{{ app.dest_path }}/{{ app.version_dir }}/{{ app.docker_compose_context }}"
