---

- hosts: all
  gather_facts: no
  pre_tasks:
    - name: もしPythonがなかったらインストール
      become: yes
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
      changed_when: False
    - name: Gather facts
      setup:
  become: yes
  roles:
    - galaxy/geerlingguy.docker
    - execute_user
    - dev_packages
    - jp_timezone
    - docker_plugin_netshare

# replicasを先にしたい
- hosts: replicas
  become: yes
  roles:
    - docker_plugin_sshfs
    - ssh_key

- hosts: master
  become: yes
  roles:
    - ssh_key
