Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "master" do |c|
    c.vm.hostname = "master"
    c.vm.box      = "generic/debian10"
    c.vm.network :private_network, ip: "192.168.34.101"
    c.vm.provider :virtualbox do |vbox|
      vbox.name   = "master"
      vbox.cpus   = 1
      vbox.memory = 1024*2
    end
  end
  config.vm.define "slave-1" do |c|
    c.vm.box      = "generic/debian9"
    c.vm.hostname = "slave-1"
    c.vm.network :private_network, ip: "192.168.34.102"
    c.vm.provider :virtualbox do |vbox|
      vbox.name   = "slave-1"
      vbox.cpus   = 1
      vbox.memory = 1024*2
    end
  end
  config.vm.define "slave-2" do |c|
    c.vm.box      = "generic/debian10"
    c.vm.hostname = "slave-2"
    c.vm.network :private_network, ip: "192.168.34.103"
    c.vm.provider :virtualbox do |vbox|
      vbox.name   = "slave-2"
      vbox.cpus   = 1
      vbox.memory = 1024*2
    end
  end
end
